# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logchan', '0002_auto_20170601_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deletion_password',
        ),
    ]
