# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logchan', '0002_auto_20170601_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(default='board', max_length=200),
            preserve_default=False,
        ),
    ]
